### PR TITLE
Cm 13.0 video

### PR DESCRIPTION
**Pull request by syphyr**
These changes add support for new power modes to the framebuffer and video drivers.

I've also found several commits to the video drivers that were partially applied and therefore needed to be re-applied.

For example, the following commits are already applied to our branch prior to any of these changes. Although, they seem to be partially applied for some reason.  I can not find any history on what happened to these commits and why there are only partially applied:

7816c44 (18 minutes ago) msm: vidc: Allow client to set turbo mode (Maheshwar Ajja)
1ffe3fb (20 minutes ago) mm-video:vidc: Set max performance level for high framerate content (Praveen Chavan)
1ef223a (29 minutes ago) msm: vidc: Add LTR feature for H264 encoder (Maheshwar Ajja)
f84f72c (41 minutes ago) msm: vidc: Remove kernel mapping on input/output buffers (Maheshwar Ajja)
55c6ad4 (6 hours ago) msm_fb: hdmi: Remove supported resolution check (Ajay Singh Parmar)

It also seems like some of the patches in our branch have been applied out of order in drivers/video/msm/.  When the LG source was applied, it replaced video code but there is no history for it.  For example, look at the history of vcd_ddl_metadata.c.

https://github.com/syphyr/android_kernel_lge_awifi/commits/cm-13.0/drivers/video/msm/vidc/1080p/ddl/vcd_ddl_metadata.c

Notice that "msm: vidc: Add LTR feature for H264 encoder" is applied in the history. Then, once "LA.AF.1.1-01910-8064.0 -> LGV500" was applied, parts of the LTR patch were removed.  Although, there is no "Blame" history that shows records of where the code changes happened.

So, since the history is not correctly displayed, I have used "diff" to manually compare the files in drivers/video/msm with Flo and compare each line of code.

Please let me know what you think.

### CODE REVIEW

**Comment by syphyr** [comment]
I removed the vidc patches because there are too many changes here.  The vidc patches will be a separate pull request.  

These video patches still need more testing because I have seen a few spontaneous reboots when waking up the device in the lock screen.

**Comment by fefifofum** [comment]
What about this, can we close it?

**Comment by syphyr** [comment]
Yes, I think the v500 uses a different framebuffer driver than flo, so these changes have some unresolved issues.  Although, maybe this commit is still useful?
https://github.com/awifi-dev/android_kernel_lge_awifi/pull/10/commits/7c924c14ea81f64b72982740b6f8e3d76a6fc7c0

**Comment by syphyr** [comment]
I will close this because there are too many problems with all these and make a new pull request with that single commit to unmap the secure memory on dtv off.

**Pull request closed without merging**
