### PR TITLE
power_supply: Don't abort when an adaptive USB charge property fails

### PR DESCRIPTION
**Pull request by syphyr**
These properties aren't always present, and their absence is making
the entire set of USB supply events abort. Make these properties'
absence non-fatal

`
    2.134765 / 05-21 09:50:03.970] power_supply usb: driver failed to report `present' property: 4294967274[    2.134796 / 05-21 09:50:03.970] power_supply usb: driver failed to report `present' property: 4294967274[    2.134887 / 05-21 09:50:03.970] power_supply pm8921-dc: driver failed to report `present' property: 4294967274[    2.134918 / 05-21 09:50:03.970] power_supply pm8921-dc: driver failed to report `present' property: 4294967274[    2.136138 / 05-21 09:50:03.970] power_supply battery: driver failed to report `present' property: 4294967274`

### CODE REVIEW

**Comment by syphyr** [comment]
1) Merged latest Flo patches (ALSA, Input, netfilter, ppp)
2) Added additional NEON/VFP patches and NEON XOR optimizations
3) Fine tuned Mach Mem Utils (memcpy, memmove)
4) Make sure cpufreq and governors manage offline cpus only
5) Fix additional buffer problems

**Comment by syphyr** [comment]
1) Merged latest Flo patches (ALSA, Input, netfilter, ppp)
2) Added additional NEON/VFP patches and NEON XOR optimizations
3) Fine tuned Mach Mem Utils (memcpy, memmove)
4) Make sure cpufreq and governors manage online cpus only
5) Fix additional buffer problems

**Comment by syphyr** [comment]
The patch for DriveDroid has been removed from this pull request because while testing, the host pc was unable to bootup from the mounted DriveDroid image.  This is probably due to selinux permissions.

**Comment by fefifofum** [comment]
Done!

**Pull request closed without merging**
